sudo: required

services:
- docker

language: java

jdk:
- openjdk7

env:

before_install:
- sudo apt-get --only-upgrade install maven3
  
script:
- mkdir -p dist
- cd base && mvn dependency:get -DartifactId=maven-ant-tasks -DgroupId=org.apache.maven -Dversion=2.1.3
- ant -lib ~/.m2/repository/org/apache/maven/maven-ant-tasks/2.1.3 dist.lin64
- cp dist/linux/*.zip ../dist
- cd ..
- ls -l dist
- docker build -t videobridge .

after_success:
- docker tag videobridge connecter/videobridge:current
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push connecter/videobridge:current
