sudo: required

services:
- docker

language: java

jdk:
- openjdk7

env:

before_install:
  
script:
- make
- docker build -t videobridge .

after_success:
- docker tag videobridge connecter/videobridge:current
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push connecter/videobridge:current
